/* DEAL ACTIONS */
export const LOAD_DEALS_BEGINS = 'LOAD_DEALS_BEGINS';
export const LOAD_DEALS_COMPLATE = 'LOAD_DEALS_COMPLATE';
export const LOAD_DEALS_ERROR = 'LOAD_DEALS_ERROR';
export const FILTER_DEALS_BY_PRICE = 'FILTER_DEALS_BY_PRICE';