/* DEAL ACTIONS */
export const LOAD_DEALS_BEGINS = 'LOAD_DEALS_BEGINS';
export const LOAD_DEALS_COMPLATE = 'LOAD_DEALS_COMPLATE';
export const LOAD_DEALS_ERROR = 'LOAD_DEALS_ERROR';
export const FILTER_DEALS_BY_PRICE = 'FILTER_DEALS_BY_PRICE';
export const UPDATE_COUNT='UPDATE_COUNT';

export const USER_DATA_BEGINS='USER_DATA_BEGINS';
export const USER_DATA='USER_DATA';
export const USER_DATA_COMPLETE='USER_DATA_COMPLETE';
export const USER_DATA_ERROR='USER_DATA_ERROR';
