/* DEAL ACTIONS */
export const LOAD_DEALS_BEGINS = 'LOAD_DEALS_BEGINS';
export const LOAD_DEALS_COMPLATE = 'LOAD_DEALS_COMPLATE';
export const LOAD_DEALS_ERROR = 'LOAD_DEALS_ERROR';
export const FILTER_DEALS_BY_PRICE = 'FILTER_DEALS_BY_PRICE';

export const LOAD_WORKERS_BEGINS ="LOAD_WORKERS_BEGINS";
export const LOAD_WORKERS_COMPLETE ="LOAD_WORKERS_COMPLETE";
export const LOAD_WORKERS_ERROR ="LOAD_WORKERS_ERROR";

export const LOAD_JOB ="LOAD_JOB";

export const LOGIN_BEGINS ="LOGIN_BEGINS";
export const LOGIN_COMPLETE ="LOGIN_COMPLETE";
export const LOGIN_ERROR ="LOGIN_ERROR";